name: eopf-zarr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - folium
  - graphviz
  - mapclassify
  - fsspec
  - numpy
  - mystmd
  - cartopy
  - gdal
  - pip
  - pip:
    - eopf==2.5.5
