name: eopf-test
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - xarray
  - folium
  - graphviz
  - mapclassify
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.7
  - bottleneck=1.4.2
  - fsspec
  - numpy=1.26.4
  - mystmd
  - cartopy
  - gdal
  - jupyter_server
  - pre-commit
  - black-jupyter
  - pip
  - pip:
      - eopf==2.5.5
      - ipykernel
      - jupyterlab-myst
